### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by xuxiaolong1029** [arjitkhullar/ide#5]
为什么你这项目启动不了，拉取你的代码安装依赖后 yarn run serve总是报错

**Comment by gptguy** [comment]
Since you are running the IDE in dev mode. Try creating a `titanrc.ts` under` src/store` with `export const nodeAddress = 'your node address'`  in it.

**Comment by xuxiaolong1029** [comment]
You're right. After creating this file, I can run your code locally.

**Comment by xuxiaolong1029** [comment]
Thank you
